Adds Aion, Akai, Boss, FTelettronica, The King of Gear, Walrus, and pedal requests
PedalPlayground/PedalPlayground.github.io pull request #1252
Opened 2022-10-25 19:29 UTC by XlosVSM

**Adds**

- 3rd Power Roosevelt Drive
- Aion Andromeda
- Aion Cerulean
- Aion Convex
- Aion Equinox
- Aion Graviton
- Aion Halo
- Aion Helios
- Aion Lumin
- Aion Phobos
- Aion Quantum
- Aion Radian
- Aion Refractor
- Aion Rift
- Aion Solaris
- Aion Solstice
- Aion Vector
- Akai E2 Headrush
- BOSS DS-1w
- BOSS OD-2R
- BOSS PQ-4
- Cry Baby GCB65 Custom Badass Dual Inductor Wah
- Cusack Tap-A-Whirl (Red)
- Deadbug Circuits 1968
- FTelettronica Tuwat Resonant Envelope Filter
- FTelettronica Utopian Fuzz
- FTelettronica Venomous Octopus
- FTelettronica Wave Reflector
- FTelettronica Weird Sound Generator Elite
- FTelettronica Zero Sum Game
- FTelettronica Zeroth Law
- Garage Tone Drive Train
- Lauren Audio Mustang
- MJM FX London Fuzz
- MJM FX Phantom Overdrive
- Oto Machines Bam
- Oto Machines Bim
- Oto Machines Boum
- Radial Engineering AC-Driver
- Seymour Duncan Vapour Trails Deluxe
- The King of Gear Feral Glitch
- VFE Klein Bottle 2022
- Walrus ARP-87 (Obsidian Series)
- Walrus Eras (Obsidian Series)
- Walrus Eras (Retro Edition)
- Walrus Julianna (Obsidian Series)
- Walrus Monument V2 (Obsidian Series)
- Walrus Slötvå (Obsidian Series)

**Fixes**

- Friedman Gold-72 images (blank space was forgotten to be removed)
- Moves Malekko Ekko 616 MKII FE to the correct position alphabetically
- Moves MXR Bass Innovations to its own section
- Removes forgotten Dunlop wahs (if a pedal on your website has gone invisible, delete it and readd it)
- Removes unused images
- Spelling
- Various file names

closes #1179
closes #1181
closes #1189
closes #1192
closes #1193
closes #1197
closes #1198
closes #1200
closes #1209
closes #1217
closes #1222
closes #1223
closes #1224
closes #1239
closes #1242
closes #1246

2022-12-17 13:39 UTC, ArislanShiva commented
Hey, just FYI I had the CTC Unobtainium done already.

2022-12-17 13:42 UTC, ArislanShiva requested changes
Also, please don't change the dimensions for the Nux switch.  Gotta account for jacks.

2023-01-15 19:12 UTC, XlosVSM commented
I am not going to add more to this pr because it is already huge in changes, and I do not want to bother people with more whens when the merge happens. @tehtrav how long before it is merged?

2023-01-21 04:16 UTC, lightyrs commented on public/data/pedals.json
> +	},
@XlosVSM Dimensions are off here. This should be:

```json
{
    "brand": "VFE",
    "name": "Klein Bottle 2022",
    "width": 5.625,
    "height": 4.63,
    "image": "vfe-klein-bottle-2022.png"
  }
```

2023-01-23 20:12 UTC, tehtrav commented
fix conflicts and I'll pull it in, sorry for the delay

2023-01-24 19:43 UTC, XlosVSM commented
@tehtrav fixed

2023-02-18 05:22 UTC, ArislanShiva requested changes
Please double check your measurements on these. 

1590BB enclosure is 3.7" wide and 4.7" tall, not counting the jacks.

2023-02-22 20:46 UTC, ZYMECORE commented
When will this merge post? This pull is almost 6 months old!

2023-02-22 21:59 UTC, ArislanShiva commented
> When will this merge post? This pull is almost 6 months old!

Every time @tehtrav goes to pull this one in there are conflicts that need to be resolved.

If @XlosVSM doesn't stop with the broader file/name edits that are causing the conflicts it's never gonna get pulled in.

2023-02-27 22:12 UTC, XlosVSM commented
@tehtrav still waiting for merge

2023-02-27 22:12 UTC, closed without merging

2023-03-14 17:59 UTC, oooctave commented
Lauren Audio Mustang is still missing from the database from this push