Update pedals.json
PedalPlayground/PedalPlayground.github.io pull request #279
Opened 2021-02-25 10:29 UTC by TMRWstudio

TC Electronic Gauss Tape Echo
	{
		"Brand": "TC Electronic",
		"Name": "Gauss Tape Echo",
		"Width": 29.13,
		"Height": 51.97,
		"Image": "gauss-tape-echo.png"
	}

2021-02-25 10:36 UTC, TMRWstudio commented
![gauss-tape-echo](https://user-images.githubusercontent.com/22024836/109141100-a216d000-775d-11eb-9882-43fa72054b15.png)

2021-03-15 18:57 UTC, tehtrav commented
Looks like this is half done, the image will need cut out and placed in the correct folders. If you don't have a way to do that I can help with that.

2021-03-17 11:20 UTC, TMRWstudio commented
Hi
I cut out the image using photoshop and converted to png. If you can direct me as to what folder I would be grateful. Thnx

2021-04-07 13:13 UTC, tehtrav requested changes
Size is incorrect, possibly in metric rather than inches. Also image needs to be put in the correct folders (see Readme instructions)

2021-05-17 16:08 UTC, closed without merging