new pedals: great eastern, milkman amp, saturnworks looper, vox v810
PedalPlayground/PedalPlayground.github.io pull request #912
Opened 2022-04-17 20:21 UTC by jhpacker

Added 4 new pedals:
great eastern fx co. small speaker overdrive
milkman the amp
saturnworks compact looper (horizontal)
vox v810 valvetone

2022-04-18 22:54 UTC, cbserra approved these changes

2022-04-19 16:45 UTC, tehtrav commented on public/data/pedals.json
> +		"Width": 2.5625
missing comma

2022-04-19 16:48 UTC, tehtrav requested changes
Fix the one small spot in the JSON and I will approve once the build errors are resolved. Thanks!

2022-04-19 16:55 UTC, jhpacker commented
thanks, sorry I missed that.

2022-04-19 21:46 UTC, XlosVSM approved these changes

2022-05-21 08:03 UTC, ArislanShiva requested changes
Hey sorry, I added the Milkman amp in my last PR from a recent request, didn't realize you had already made it.  You can remove yours now to clear the merge conflict.  Sorry!

2022-06-02 18:59 UTC, merged